baseURL = "https://jirex.netlify.com/"
languageCode = "en-us"
title = "jirex's Blog"
theme = "redlounge"

[params]
	sidebartitle = "jirex's Blog"
	sidebartagline = "Emacs, Org Mode, Docker\niOS, Python, Php, Vue\nProgrammer"

[[menu.main]]
    name = "Blog"
    url = "/posts"

[[menu.social]]
	pre = "<i class='fa fa-twitter'></i>"
    url = "https://www.twitter.com/jirex1119"
    identifier = "twitter"
[[menu.social]]
	pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/jirex"
    identifier = "github"
